name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker Image
    runs-on: [veila]
    outputs:
      image_tag: latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t veila-server:latest .

  deploy-demo:
    name: Deploy for Front-end Development
    needs: build
    runs-on: [veila]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.development file
        run: echo "${{ secrets.ENV_DEVELOPMENT }}" > .env.development

      - name: Run demo container from prebuilt image
        run: |
          docker stop veila-dev-be || true
          docker rm veila-dev-be || true
          docker run -d --name veila-dev-be \
            --env-file .env.development \
            -e PORT=1205 \
            -e START_COMMAND=deploy:development \
            -v /var/lib/veila/uploads:/usr/src/app/uploads \
            -p 1205:3000 \
            -p 1201:3001 \
            veila-server:latest

  deploy-production:
    name: Deploy for Production
    needs: build
    runs-on: [veila]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.production file
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: Run production container from prebuilt image
        run: |
          docker stop veila-prod-be || true
          docker rm veila-prod-be || true
          docker run -d --name veila-prod-be \
            --env-file .env.production \
            -e PORT=1206 \
            -e START_COMMAND=deploy:production \
            -v /var/lib/veila/uploads:/usr/src/app/uploads \
            -p 1206:3000 \
            -p 1202:3001 \
            veila-server:latest

  cleanup:
    name: Cleanup
    runs-on: [veila]
    needs: [build, deploy-demo, deploy-production]
    steps:
      - name: Cleanup unused images
        run: |
          docker image prune -f
          docker system prune -f
